"""empty message

Revision ID: 41e901482a83
Revises: c4bb30628fe5
Create Date: 2021-02-07 16:04:21.054950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e901482a83'
down_revision = 'c4bb30628fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('hoursPerSession', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'hoursPerSession')
    # ### end Alembic commands ###
