"""empty message

Revision ID: c4bb30628fe5
Revises: 3d008bb5d4ee
Create Date: 2021-02-06 15:07:46.383246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bb30628fe5'
down_revision = '3d008bb5d4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'checked')
    # ### end Alembic commands ###
